Repository GEON-PPANG/GEON-PPANG-iOS, pull requests merged in 2023-08, with the labels that each got.

#111 [Refact] #110 - 코드 컨벤션 수정
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Network/API/Home/HomeAPI.swift
  GEON-PPANG-iOS/Global/Network/API/Search/SearchAPI.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/BakeryListResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Home/HomeBestBakeryResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Home/HomeBestReviewResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/MyPage/MyReviewsResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Search/SearchResponseDTO.swift
  GEON-PPANG-iOS/Global/Protocol/BakeryTypeProtocol.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/InfoCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/TitleCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Cell/BakeryCollectionViewListCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Cell/BakeryFilterCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/Model/BakeryFilterItems.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryFilterView.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryListTopView.swift
  GEON-PPANG-iOS/Presentation/Common/BottomSheet/BottomSheetAppearView.swift
  GEON-PPANG-iOS/Presentation/Common/BottomSheet/CommonBottomSheet.swift
  GEON-PPANG-iOS/Presentation/Common/Button/BookmarkButton.swift
  GEON-PPANG-iOS/Presentation/Common/Button/CommonButton.swift
  GEON-PPANG-iOS/Presentation/Common/ImageView/GradientImageView.swift
  GEON-PPANG-iOS/Presentation/Common/Label/PaddingLabel.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/MarkStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/RegionStackView.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/CommonTextView.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/SearchTextField.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/SignInTextField.swift
  GEON-PPANG-iOS/Presentation/Common/View/LineView.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterBreadTypeViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterCompleteViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterIngredientViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterPurposeViewController.swift
  GEON-PPANG-iOS/Presentation/Home/HomeBakeryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/HomeBottomCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/Home/Views/HomeHeaderView.swift
  GEON-PPANG-iOS/Presentation/Home/Views/HomeTopView.swift
  GEON-PPANG-iOS/Presentation/MyReviews/Cell/MyReviewsCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsViewController.swift
  GEON-PPANG-iOS/Presentation/MyReviews/Views/MyReviewsHeaderView.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/Onboarding/ViewControllers/OnboardingViewController.swift
  GEON-PPANG-iOS/Presentation/Search/Cell/EmptyCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  GEON-PPANG-iOS/Presentation/Search/Views/SearchNavigationView.swift
  GEON-PPANG-iOS/Presentation/Search/Views/SearchResultView.swift
  GEON-PPANG-iOS/Presentation/SignIn/Email/EmailViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/NickName/NickNameViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/Password/PasswordViewController.swift
  GEON-PPANG-iOS/Presentation/Tabbar/TabBarController.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/BakeryOverviewView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/ViewController/WriteReviewViewController.swift
Labels: 🍒 정은 🍒, 💭 Refact

#117 [Refact] #114 - 김창균 코드 리팩토링
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/Global/Extensions/UI/Int+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UIButton+.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/BakeryDetailResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/WrittenReviewsResponseDTO.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/InfoCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/MenuCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/ReviewCategoryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/TitleCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/WrittenReviewsCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/BakeryDetailCollectionViewFooter.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/BakeryDetailCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/ReviewProgressView.swift
  GEON-PPANG-iOS/Presentation/Common/Button/ReviewSortButton.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/BookmarkReviewNumberStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/BreadTypeStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/IconLabelStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/ReviewCategoryStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/ReviewProgressBarStackView.swift
  GEON-PPANG-iOS/Presentation/Common/View/DrawDashLineView.swift
  GEON-PPANG-iOS/Presentation/Onboarding/ViewControllers/OnboardingViewController.swift
Labels: 🍎 창균 🍎, 💭 Refact

#113 [Fix] #112 - Bundle ID 변경 및 파이어베이스 재연동
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/InfoCollectionViewCell.swift
  GEON-PPANG-iOS/Resource/GoogleService-Info.plist
Labels: 🧊 Fix, 🍒 정은 🍒

#134 [Feat] #119 - 홈 뷰 바뀐 디자인 적용
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Extensions/Design/UIImage+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/CertificationMarkResponseType.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/NearStationResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/RecommendKeywordResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Home/HomeBestBakeryResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Home/HomeBestReviewResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Home/HomeCommonResponseDTO.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/Common/Base/BaseViewController.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/IconWithTextStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/RegionStackView.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/SearchTextField.swift
  GEON-PPANG-iOS/Presentation/Home/HomeBakeryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/HomeBottomCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsViewController.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/Password/PasswordViewController.swift
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_review_16px_400.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_review_16px_400.imageset/ic_review_16px_400@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_review_16px_400.imageset/ic_review_16px_400@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_review_16px_400.imageset/ic_review_16px_400@3x.png
Labels: 🍞 Feat, 🍒 정은 🍒

#135 [Feat] #127 - 탭 바 바뀐 디자인 적용
  GEON-PPANG-iOS/Global/Enum/TabBarItem.swift
  GEON-PPANG-iOS/Global/Extensions/UI/TabBar+.swift
  GEON-PPANG-iOS/Presentation/Tabbar/TabBarController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#124 [Feat] #118 - 변경된 필터 뷰 디자인 및 API 적용
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/Global/Enum/FilterEnum.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UILabel+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/BreadRequestType.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/NutrientRequestType.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Filter/FilterRequestDTO.swift
  GEON-PPANG-iOS/Presentation/Common/Button/CommonButton.swift
  GEON-PPANG-iOS/Presentation/Common/NavigationBar/CustomNavigationBar.swift
  GEON-PPANG-iOS/Presentation/Filter/Model/FilterCellModel.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterBreadTypeViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterCompleteViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterIngredientViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterPurposeViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/Views/FilterCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Filter/Views/FilterCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/Filter/Views/FilterDiffableDataSource.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/NickName/NickNameViewController.swift
Labels: 🍞 Feat, 🍏 성민 🍏

#126 [Feat] #122 - 변경된 온보딩 뷰 UI 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/GEON-PPANG-iOS.entitlements
  GEON-PPANG-iOS/Global/Extensions/Design/UIImage+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/Onboarding/ViewControllers/OnboardingViewController.swift
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/AppleSocialLogin.imageset/AppleSocialLogin.pdf
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/AppleSocialLogin.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/KakaoSocialLogin.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/KakaoSocialLogin.imageset/KakaoSocialLogin.pdf
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/apple_login_button_56px.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/apple_login_button_56px.imageset/apple_login_button_56px@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/apple_login_button_56px.imageset/apple_login_button_56px@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/apple_login_button_56px.imageset/apple_login_button_56px@3x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/google_login_button_56px.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/google_login_button_56px.imageset/google_login_button_56px@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/google_login_button_56px.imageset/google_login_button_56px@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/google_login_button_56px.imageset/google_login_button_56px@3x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/kakao_login_button_56px.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/kakao_login_button_56px.imageset/kakao_login_button_56px@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/kakao_login_button_56px.imageset/kakao_login_button_56px@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/kakao_login_button_56px.imageset/kakao_login_button_56px@3x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/naver_login_button_56px.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/naver_login_button_56px.imageset/naver_login_button_56px@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/naver_login_button_56px.imageset/naver_login_button_56px@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/social_login/naver_login_button_56px.imageset/naver_login_button_56px@3x.png
Labels: 🍞 Feat, 🍏 성민 🍏

#129 [Feat] #125 - 리뷰 작성 바뀐 UI 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Extensions/Design/UIImage+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/TitleCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Cell/BakeryCollectionViewListCell.swift
  GEON-PPANG-iOS/Presentation/Common/BottomSheet/BottomSheetAppearView.swift
  GEON-PPANG-iOS/Presentation/Common/BottomSheet/CommonBottomSheet.swift
  GEON-PPANG-iOS/Presentation/Common/Button/CommonButton.swift
  GEON-PPANG-iOS/Presentation/Common/Cell/DescriptionCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Common/Label/BookmarkCountLabel.swift
  GEON-PPANG-iOS/Presentation/Common/Label/RegionLabel.swift
  GEON-PPANG-iOS/Presentation/Common/NavigationBar/CustomNavigationBar.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/MarkStackView.swift
  GEON-PPANG-iOS/Presentation/Home/HomeBakeryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/MyReviews/Cell/MyReviewsCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsViewController.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/Email/EmailViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/NickName/NickNameViewController.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/BakeryOverviewView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/ReviewDetailTextView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/WriteReviewBottomSheetView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/ViewController/WriteReviewViewController.swift
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/memo_32px.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/memo_32px.imageset/memo_32px@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/memo_32px.imageset/memo_32px@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/memo_32px.imageset/memo_32px@3x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/smile_32px.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/smile_32px.imageset/smile_32px@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/smile_32px.imageset/smile_32px@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/smile_32px.imageset/smile_32px@3x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_map.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_map.imageset/ic_map.pdf
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_review_bread.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_review_bread.imageset/icon_review_bread.pdf
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_smile.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_smile.imageset/icon_smile.pdf
Labels: 🍞 Feat, 🍏 성민 🍏

#136 [Feat] #123 - 검색 뷰 바뀐 디자인 적용
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Application/SceneDelegate.swift
  GEON-PPANG-iOS/Global/Enum/FilterEnum.swift
  GEON-PPANG-iOS/Global/Network/API/Bakery/BakeryAPI.swift
  GEON-PPANG-iOS/Global/Network/API/MyPage/MyPageAPI.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/BakeryListResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/BakeryCommonListResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/CertificationMarkResponseType.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Home/HomeBestBakeryResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/MyPage/MyReviewsResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Search/SearchResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/Search/SearchService.swift
  GEON-PPANG-iOS/Global/Protocol/BakeryTypeProtocol.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Cell/BakeryCommonCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryListTopView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/BreadTypeStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/IconWithTextStackView.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPageCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/MyReviews/Cell/MyReviewsCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsViewController.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/Search/Cell/EmptyCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  GEON-PPANG-iOS/Presentation/Search/Views/SearchResultHeaderView.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#131 [Feat] #130 - Welcome View 추가
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/Welcome/ViewControllers/WelcomeViewController.swift
Labels: 🍞 Feat, 🍏 성민 🍏

#139 [Feat] #138 - 공통 버튼 및 바텀시트 바뀐 디자인 적용
  GEON-PPANG-iOS/Global/Extensions/Design/UIImage+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/Common/BottomSheet/CommonBottomSheet.swift
  GEON-PPANG-iOS/Presentation/Common/Button/CommonButton.swift
  GEON-PPANG-iOS/Presentation/SignIn/Email/EmailViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/NickName/NickNameViewController.swift
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/icon_crying.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/icon_crying.imageset/icon_crying.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/icon_crying.imageset/icon_crying@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/icon_crying.imageset/icon_crying@3x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/icon_sad.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/icon_sad.imageset/icon_sad.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/icon_sad.imageset/icon_sad@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/icon_sad.imageset/icon_sad@3x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/sad_32px.imageset/sad_32px@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/sad_32px.imageset/sad_32px@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/emoji/sad_32px.imageset/sad_32px@3x.png
Labels: 🍞 Feat, 🍒 정은 🍒
