Repository GEON-PPANG/GEON-PPANG-iOS, pull requests merged in 2023-09, with the labels that each got.

#140 [Feat] #120 - 회원가입 뷰 바뀐 디자인 적용
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/Global/Enum/SignInPropertyType.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UIViewController+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/CommonTextView.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/SignInTextField.swift
  GEON-PPANG-iOS/Presentation/NickName/NickNameViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/NickName/NickNameViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/Password/PasswordViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/SignInViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#149 [Feat] #121 - 소셜로그인 기능들 추가해둔 PR
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Application/AppDelegate.swift
  GEON-PPANG-iOS/Application/SceneDelegate.swift
  GEON-PPANG-iOS/Global/Network/Base/Config.swift
  GEON-PPANG-iOS/Presentation/Onboarding/ViewControllers/OnboardingViewController.swift
  GEON-PPANG-iOS/Resource/Info.plist
Labels: 🍞 Feat, 🍏 성민 🍏

#142 [Feat] #141 -로그인 UI 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Enum/SignInPropertyType.swift
  GEON-PPANG-iOS/Global/Extensions/Design/UIColor+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/LogIn/ViewController/LogInViewController.swift
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Gray_500.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Gray_Scale/Contents.json
Labels: 🍞 Feat, 🍒 정은 🍒

#144 [Feat] #143 - 닉네임뷰 바뀐 디자인 적용
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/NickName/NickNameViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#147 [Feat] #132 - mypage VC 바뀐 UI 적용
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/Global/Enum/AlertEnum.swift
  GEON-PPANG-iOS/Global/Enum/MyPageSectionEnum.swift
  GEON-PPANG-iOS/Global/Extensions/Design/UIColor+.swift
  GEON-PPANG-iOS/Global/Extensions/Design/UIImage+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Literals/UrlLiteral.swift
  GEON-PPANG-iOS/Global/Protocol/DiffableDataSourceProtocol.swift
  GEON-PPANG-iOS/Presentation/Common/Alert/AlertView.swift
  GEON-PPANG-iOS/Presentation/Common/Alert/AlertViewController.swift
  GEON-PPANG-iOS/Presentation/Common/WebView/WebViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/Views/FilterDiffableDataSource.swift
  GEON-PPANG-iOS/Presentation/MyPage/Model/MyPageModel.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPageCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPageCollectionViewFooter.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPageCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPageDataSource.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPagePurposeChipView.swift
  GEON-PPANG-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_smile_86px.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_smile_86px.imageset/ic_smile.pdf
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/alert-gray.colorset/Contents.json
Labels: 🍞 Feat, 🍏 성민 🍏

#152 [Feat] #150 - 이메일 중복 확인 API 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Network/API/Auth/AuthAPI.swift
  GEON-PPANG-iOS/Global/Network/Base/URLConstant.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Auth/AuthRequestDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/Auth/AuthService.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/CommonTextView.swift
  GEON-PPANG-iOS/Presentation/NickName/NickNameViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/SignInViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#146 [Feat] #145 - 홈 뷰 말풍선 구현 및 홈 뷰관련 API 연동
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Extensions/Design/UIImage+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Network/API/Filter/FilterAPI.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Filter/FilterResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/Filter/FilterService.swift
  GEON-PPANG-iOS/Presentation/Home/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/Home/Views/BubbleView.swift
  GEON-PPANG-iOS/Presentation/Home/Views/HomeHeaderView.swift
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_bubble.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_bubble.imageset/img_bubble.pdf
Labels: 🍞 Feat, 🍒 정은 🍒

#155 [Feat] #133 - 내가 쓴 리뷰 디자인 적용
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Presentation/Common/BottomSheet/BottomSheetAppearView.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsViewController.swift
  GEON-PPANG-iOS/Presentation/MyReviews/Views/MyReviewsHeaderView.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#154 [Feat] #153 - 빵집 리스트 UI 수정 및 API 연결
  .swiftlint.yml
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Extensions/Design/UIImage+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/Encodable+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Network/API/Bakery/BakeryAPI.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/BakeryRequestDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/BakeryCommonListResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/Bakery/BakeryService.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Cell/BakeryCommonCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Cell/BakeryFilterCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/SortBottomSheetViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryFilterView.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryListTopView.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/SortBakeryFilterView.swift
  GEON-PPANG-iOS/Presentation/LogIn/ViewController/LogInViewController.swift
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_filter_check.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_filter_check.imageset/ic_filter_check.pdf
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_filter_unchecked.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_filter_unchecked.imageset/ic_filter_unchecked.pdf
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/ready-made_buttons/bakery_filter_button.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/ready-made_buttons/bakery_filter_button.imageset/bakery_filter_button.pdf
Labels: 🍞 Feat, 🍒 정은 🍒

#160 [Feat] #159 - 로그인 API 연결
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Network/API/Auth/AuthAPI.swift
  GEON-PPANG-iOS/Global/Network/Base/AuthPlugin.swift
  GEON-PPANG-iOS/Global/Network/Base/NetworkConstant.swift
  GEON-PPANG-iOS/Global/Network/Base/URLConstant.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Auth/AuthRequestDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/Auth/AuthService.swift
  GEON-PPANG-iOS/Presentation/Home/HomeBottomCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/LogIn/ViewController/LogInViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/SignInViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#165 [Fix] #162 - Empty Cell 레이아웃 수정
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Enum/BakeryListEmptyType.swift
  GEON-PPANG-iOS/Global/Utils/LayoutUtils.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsViewController.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/Search/Cell/EmptyCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_bookmark.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_bookmark.imageset/img_no_bookmark.pdf
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_bookmark.imageset/img_no_bookmark@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_bookmark.imageset/img_no_bookmark@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_bookmark.imageset/img_no_bookmark@3x.png
Labels: 🧊 Fix, 🍒 정은 🍒

#167 [Feat] #163 - 회원 가입 비밀번호 분기처리
  GEON-PPANG-iOS/Presentation/SignIn/SignInViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#166 [Feat] #148 - 상세페이지 뷰 바뀐 디자인 적용
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/BakeryDetailResponseDTO.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/InfoCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/BakeryDetailCollectionViewFooter.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/BakeryDetailCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/BreadTypeStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/IconLabelStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/LinkButtonStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/RegionStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/ReviewCategoryStackView.swift
Labels: 🍞 Feat, 🍎 창균 🍎

#174 [Fix] #172 - 몇가지 버그 수정 & 자잘한 작업
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Review/WriteReviewRequestDTO.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterViewController.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/BakeryOverviewView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/ViewController/ReviewViewController.swift
Labels: 🧊 Fix, 🍏 성민 🍏

#180 [Feat] #157 - 상세페이지 리뷰 셀 바뀐 디자인 적용
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/WrittenReviewsResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/BreadResponseType.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/InfoCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/ReviewCategoryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/WrittenReviewsCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/BakeryDetailCollectionViewFooter.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/ReviewProgressView.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Cell/BakeryCommonCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/BreadTypeStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/LinkButtonStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/MarkStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/RegionStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/ReviewCategoryStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/ReviewProgressBarStackView.swift
Labels: 🍞 Feat, 🍎 창균 🍎

#179 [Fix] #173 - 디자인 이슈 수정
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Enum/SignInPropertyType.swift
  GEON-PPANG-iOS/Global/Extensions/UI/String+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UICollectionView+.swift
  GEON-PPANG-iOS/Global/Utils/LayoutUtils.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Cell/BakeryCommonCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/SortBakeryFilterView.swift
  GEON-PPANG-iOS/Presentation/Common/Button/IconWithTextView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/MarkStackView.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/CommonTextView.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/SignInTextField.swift
  GEON-PPANG-iOS/Presentation/Home/HomeBakeryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/HomeBottomCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/LogIn/ViewController/LogInViewController.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsViewController.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/SignInViewController.swift
Labels: 🧊 Fix, 🍒 정은 🍒

#184 [Setting] #178 - 데이터 택소노미 세팅
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/Application/AppDelegate.swift
  GEON-PPANG-iOS/Global/AnalyticManager/AnalyticManager.swift
  GEON-PPANG-iOS/Global/AnalyticManager/AnalyticManagerEvent+.swift
  GEON-PPANG-iOS/Global/AnalyticManager/AnalyticManagerEvent.swift
  GEON-PPANG-iOS/Global/AnalyticManager/AnalyticManagerEventProtocol.swift
  GEON-PPANG-iOS/Global/AnalyticManager/AnalyticManagerProtocol.swift
  GEON-PPANG-iOS/Global/AnalyticManager/AnalyticManagerUser.swift
  GEON-PPANG-iOS/Global/Network/Base/Config.swift
  GEON-PPANG-iOS/Presentation/SignIn/SignInViewController.swift
  GEON-PPANG-iOS/Resource/Info.plist
Labels: 🍭 Setting, 🍒 정은 🍒

#187 [Feat] #181 - 상세페이지 바텀시트 버튼들 바뀐 디자인 적용 및 로직 수정
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/Common/View/DetailBottomView.swift
  GEON-PPANG-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/ready-made_buttons/bookmark_button_disable.imageset/bookmark_button_disable@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/ready-made_buttons/bookmark_button_disable.imageset/bookmark_button_disable@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/ready-made_buttons/bookmark_button_disable.imageset/bookmark_button_disable@3x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/ready-made_buttons/bookmark_button_enable.imageset/bookmark_button_enable@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/ready-made_buttons/bookmark_button_enable.imageset/bookmark_button_enable@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/ready-made_buttons/bookmark_button_enable.imageset/bookmark_button_enable@3x.png
Labels: 🍞 Feat, 🍎 창균 🍎

#188 [Feat] #182 - 상세페이지 웹 연결
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/InfoCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/Common/NavigationBar/CustomNavigationBar.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/LinkButtonStackView.swift
Labels: 🍞 Feat, 🍎 창균 🍎

#189 [Feat] #185 - General, Home, List, Onboarding 데이터 택소노미 적용
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Application/AppDelegate.swift
  GEON-PPANG-iOS/Global/AnalyticManager/AnalyticManagerEvent+.swift
  GEON-PPANG-iOS/Global/Enum/AnalyticEventType.swift
  GEON-PPANG-iOS/Global/Utils/Utils.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/SortBottomSheetViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryFilterView.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/LogIn/ViewController/LogInViewController.swift
  GEON-PPANG-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsViewController.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/SignInViewController.swift
  GEON-PPANG-iOS/Presentation/WriteReview/ViewController/ReviewViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#194 [Feat] #161 - 회원 가입 API 연결
  GEON-PPANG-iOS/Global/Network/API/Filter/FilterAPI.swift
  GEON-PPANG-iOS/Presentation/Common/Button/CommonButton.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/CommonTextView.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/SearchTextField.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsViewController.swift
  GEON-PPANG-iOS/Presentation/MyReviews/Views/MyReviewsHeaderView.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/NickName/NickNameViewController.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  GEON-PPANG-iOS/Presentation/Search/Views/SearchNavigationView.swift
  GEON-PPANG-iOS/Presentation/SignIn/SignInViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#196 [Feat] #193 - 소셜로그인 (카카오, 애플) 플로우 완성
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Keychain/KeychainKey.swift
  GEON-PPANG-iOS/Global/Keychain/KeychainService.swift
  GEON-PPANG-iOS/Global/Network/API/Auth/AuthAPI.swift
  GEON-PPANG-iOS/Global/Network/API/Member/MemberAPI.swift
  GEON-PPANG-iOS/Global/Network/Base/NetworkConstant.swift
  GEON-PPANG-iOS/Global/Network/Base/URLConstant.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Auth/AuthRequestDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Auth/DeleteUserResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Auth/NicknameRequestDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Member/FetchNicknameResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Member/SetNicknameResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/Auth/AuthService.swift
  GEON-PPANG-iOS/Global/Network/Service/Member/MemberService.swift
  GEON-PPANG-iOS/Global/Network/Service/Social/KakaoService.swift
  GEON-PPANG-iOS/Global/Utils/Utils.swift
  GEON-PPANG-iOS/Presentation/Common/Alert/AlertViewController.swift
  GEON-PPANG-iOS/Presentation/LaunchScreen/LaunchScreenViewController.swift
  GEON-PPANG-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  GEON-PPANG-iOS/Presentation/NickName/NickNameViewController.swift
  GEON-PPANG-iOS/Presentation/Onboarding/ViewControllers/OnboardingViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/SignInViewController.swift
Labels: 🍞 Feat, 🍏 성민 🍏

#198 [Setting] #195 - 오류 로그 툴 센트리 세팅
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/Application/AppDelegate.swift
  GEON-PPANG-iOS/Global/Network/Base/Config.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/NickName/NickNameViewController.swift
  GEON-PPANG-iOS/Resource/Info.plist
Labels: 🍭 Setting, 🍒 정은 🍒

#199 [Feat] #183 - 리뷰 신고하기 뷰 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/Global/Extensions/UI/UIViewController+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/InfoCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/WrittenReviewsCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/BakeryDetailCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/ReviewProgressView.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/SortBakeryFilterView.swift
  GEON-PPANG-iOS/Presentation/Common/NavigationBar/CustomNavigationBar.swift
  GEON-PPANG-iOS/Presentation/Common/View/DetailBottomView.swift
  GEON-PPANG-iOS/Presentation/Report/View/DetailReasonTextView.swift
  GEON-PPANG-iOS/Presentation/Report/ViewController/ReportViewController.swift
Labels: 🍞 Feat, 🍎 창균 🍎

#200 [Feat] #197 - 앰플리튜드 UserID 및 디자인 오류 수정
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/AnalyticManager/AnalyticManager.swift
  GEON-PPANG-iOS/Global/Extensions/Design/UIImage+.swift
  GEON-PPANG-iOS/Global/Keychain/KeychainService.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Network/API/Auth/AuthAPI.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/TitleCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Cell/BakeryCommonCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/SearchTextField.swift
  GEON-PPANG-iOS/Presentation/Home/HomeBakeryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/LogIn/ViewController/LogInViewController.swift
  GEON-PPANG-iOS/Presentation/NickName/NickNameViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/SignInViewController.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/BakeryOverviewView.swift
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/100.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/1024.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/114.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/120.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/144.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/152.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/167.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/180.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/20.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/29.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/40.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/50.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/57.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/58.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/60.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/72.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/76.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/80.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/87.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/ready-made_buttons/img_loading_large.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/ready-made_buttons/img_loading_large.imageset/loading_image_3.pdf
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/ready-made_buttons/img_loading_medium.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/ready-made_buttons/img_loading_medium.imageset/loading_image_2.pdf
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/ready-made_buttons/img_loading_small.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/ready-made_buttons/img_loading_small.imageset/loading_image.pdf
  GEON-PPANG-iOS/Resource/Info.plist
Labels: 🍞 Feat, 🍒 정은 🍒

#207 [Setting] #206 - 오픈 소스 라이선스 세팅
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Settings.bundle/LicensePlist.latest_result.txt
  Settings.bundle/LicensePlist.plist
  Settings.bundle/LicensePlist/Alamofire.plist
  Settings.bundle/LicensePlist/Amplitude-iOS.plist
  Settings.bundle/LicensePlist/Kingfisher.plist
  Settings.bundle/LicensePlist/Moya.plist
  Settings.bundle/LicensePlist/ReactiveSwift.plist
  Settings.bundle/LicensePlist/RxSwift.plist
  Settings.bundle/LicensePlist/SnapKit.plist
  Settings.bundle/LicensePlist/Then.plist
  Settings.bundle/LicensePlist/analytics-connector-ios.plist
  Settings.bundle/LicensePlist/kakao-ios-sdk.plist
  Settings.bundle/LicensePlist/sentry-cocoa.plist
  Settings.bundle/Root.plist
  Settings.bundle/en.lproj/Root.strings
Labels: 🍭 Setting, 🍒 정은 🍒

#203 [Feat] #202 - 상세페이지 리뷰 셀 엠티뷰 구현
  GEON-PPANG-iOS/Global/Enum/BakeryListEmptyType.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/BakeryDetailCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/IconLabelStackView.swift
  GEON-PPANG-iOS/Presentation/Search/Cell/EmptyCollectionViewCell.swift
Labels: 🍞 Feat, 🍎 창균 🍎

#205 [Fix] #204 - QA 수정사항 반영
  GEON-PPANG-iOS/Global/Extensions/UI/String+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/Common/BottomSheet/BottomSheetAppearView.swift
  GEON-PPANG-iOS/Presentation/Common/BottomSheet/CommonBottomSheet.swift
  GEON-PPANG-iOS/Presentation/Common/Button/CommonButton.swift
  GEON-PPANG-iOS/Presentation/Common/Cell/DescriptionCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/SearchTextField.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterViewController.swift
  GEON-PPANG-iOS/Presentation/Home/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/NickName/NickNameViewController.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/WriteReviewBottomSheetView.swift
Labels: 🧊 Fix, 🍒 정은 🍒
