Repository GEON-PPANG/GEON-PPANG-iOS, pull requests merged in 2023-07, with the labels that each got.

#7 [Add] #6 - 필요한 Extention 및 SPM 추가
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/Global/Extensions/Design/UIColor+.swift
  GEON-PPANG-iOS/Global/Extensions/Design/UIFont+.swift
  GEON-PPANG-iOS/Global/Extensions/Design/UIImage+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/NSObject+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UICollectionView.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UILabel+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UIScreen+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UIStackView+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UITableView.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UITextField+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UITextView+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UIView.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UIViewController+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
Labels: 🍧 Add, 🍒 정은 🍒

#9 [Setting] #8 - Crashlytics 세팅
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS.xcodeproj/xcshareddata/xcschemes/GEON-PPANG-iOS.xcscheme
  GEON-PPANG-iOS/Application/AppDelegate.swift
  GEON-PPANG-iOS/Application/SceneDelegate.swift
  GEON-PPANG-iOS/Resource/GoogleService-Info.plist
Labels: 🍭 Setting, 🍒 정은 🍒

#11 [Setting] #10 - Font 추가 및 세팅
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Extensions/Design/UIFont+.swift
  GEON-PPANG-iOS/Resource/Fonts/Pretendard-Bold.otf
  GEON-PPANG-iOS/Resource/Fonts/Pretendard-Medium.otf
  GEON-PPANG-iOS/Resource/Info.plist
Labels: 🧊 Fix, 🍭 Setting, 🍎 창균 🍎

#14 [Feat] #13 - BaseViewController 추가
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Presentation/Common/Base/BaseViewController.swift
Labels: 🍞 Feat, 🍏 성민 🍏

#22 [Setting] #17 - 컬러 에셋 추가 및 세팅
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Extensions/Design/UIColor+.swift
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Background_1.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Background_2.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Error.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Gray_Scale/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Gray_Scale/gray-100.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Gray_Scale/gray-200.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Gray_Scale/gray-300.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Gray_Scale/gray-400.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Gray_Scale/gray-50.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Gray_Scale/gray-500.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Gray_Scale/gray-600.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Gray_Scale/gray-700.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Gray_Scale/gray-800.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Main_1.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Main_2.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Main_3.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Point_1.colorset/Contents.json
  GEON-PPANG-iOS/Resource/Colors/Colors.xcassets/Point_2.colorset/Contents.json
Labels: 🍭 Setting, 🍎 창균 🍎

#25 [Feat] #24 - 탭바 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Application/SceneDelegate.swift
  GEON-PPANG-iOS/Global/Extensions/Design/UIImage+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/CALayer+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/TabBar+.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  GEON-PPANG-iOS/Presentation/Tabbar/TabBarController.swift
  GEON-PPANG-iOS/Presentation/Tabbar/TabBarItem.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#28 [Feat] #26 - 홈 상단 UI 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Application/SceneDelegate.swift
  GEON-PPANG-iOS/Global/Enum/Enum.swift
  GEON-PPANG-iOS/Global/Enum/SearchEnum.swift
  GEON-PPANG-iOS/Global/Enum/TabBarItem.swift
  GEON-PPANG-iOS/Global/Extensions/UI/TabBar+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UICollectionView.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UILabel+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UITextField+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Utils/Utils.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/SearchTextField.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/Home/Views/HomeTopView.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  GEON-PPANG-iOS/Presentation/ViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#35 [Feat] #29 - 홈 컬렉션뷰 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Extensions/UI/CALayer+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/CGFloat+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UIView+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/Common/Button/BookmarkButton.swift
  GEON-PPANG-iOS/Presentation/Common/ImageView/GradientImageView.swift
  GEON-PPANG-iOS/Presentation/Common/Label/PaddingLabel.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/MarkStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/RegionStackView.swift
  GEON-PPANG-iOS/Presentation/Home/Model/HomeBestBakeryResponseDTO.swift
  GEON-PPANG-iOS/Presentation/Home/Model/HomeBestReviewResponseDTO.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeBakeryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeBottomCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/Home/Views/HomeHeaderView.swift
  GEON-PPANG-iOS/Presentation/Home/Views/HomeTopView.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#27 [Feat] #21 - 공통 버튼 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Protocol/Protocol.swift
  GEON-PPANG-iOS/Presentation/Common/Button/CommonButton.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#30 [Feat] #16 - 리뷰 작성 VC UI 우선 구현
  .swiftlint.yml
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Extensions/UI/UIViewController+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Network/Model/Bakery/WriteReviewDTO.swift
  GEON-PPANG-iOS/Presentation/Common/LineView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/Model/LikeModel.swift
  GEON-PPANG-iOS/Presentation/WriteReview/Model/RecommendationModel.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/BakeryOverviewView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/OptionsCollection/OptionsCollectionView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/OptionsCollection/OptionsCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/OptionsCollection/OptionsCollectionViewFlowLayout.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/OptionsCollection/OptionsCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/ReviewDetailTextView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/ViewController/WriteReviewViewController.swift
Labels: 🍞 Feat, 🍏 성민 🍏

#37 [Feat] #36 - 빵집 리스트뷰 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryFilterCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/Model/BakeryFilterItems.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/Model/BakeryListResponseDTO.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryFilterView.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryListTopView.swift
  GEON-PPANG-iOS/Presentation/Common/LineView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/MarkStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/RegionStackView.swift
  GEON-PPANG-iOS/Presentation/Home/Model/HomeBestBakeryResponseDTO.swift
  GEON-PPANG-iOS/Presentation/Home/Model/HomeBestReviewResponseDTO.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeBakeryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/Home/Views/HomeTopView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/OptionsCollection/OptionsCollectionViewFlowLayout.swift
  GEON-PPANG-iOS/Presentation/WriteReview/ViewController/WriteReviewViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#41 [Feat] #40 - 검색뷰 UI 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Protocol/BakeryTypeProtocol.swift
  GEON-PPANG-iOS/Global/Protocol/Protocol.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/Model/BakeryListResponseDTO.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryFilterView.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryListTopView.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeBottomCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Search/Model/SearchResponseDTO.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/EmptyCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  GEON-PPANG-iOS/Presentation/Search/Views/SearchNavigationView.swift
  GEON-PPANG-iOS/Presentation/Search/Views/SearchResultView.swift
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_bookmark.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_bookmark.imageset/img_no_bookmark.svg
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_bookmark.imageset/img_no_bookmark@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_bookmark.imageset/img_no_bookmark@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_bookmark.imageset/img_no_bookmark@3x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_myreview.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_myreview.imageset/img_no_myreview@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_myreview.imageset/img_no_myreview@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_myreview.imageset/img_no_myreview@3x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_review.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_review.imageset/img_no_review.svg
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_review.imageset/img_no_review@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_review.imageset/img_no_review@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_review.imageset/img_no_review@3x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_search_result.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_search_result.imageset/img_no_search_result.svg
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_search_result.imageset/img_no_search_result@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_search_result.imageset/img_no_search_result@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_no_search_result.imageset/img_no_search_result@3x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_search.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_search.imageset/img_search.svg
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_search.imageset/img_search@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_search.imageset/img_search@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_search.imageset/img_search@3x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_server_maintenance.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_server_maintenance.imageset/img_server_maintenance.svg
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_server_maintenance.imageset/img_server_maintenance@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_server_maintenance.imageset/img_server_maintenance@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_server_maintenance.imageset/img_server_maintenance@3x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_welcome.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_welcome.imageset/img_welcome.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_welcome.imageset/img_welcome@1x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_welcome.imageset/img_welcome@2x.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_welcome.imageset/img_welcome@3x.png
Labels: 🍞 Feat, 🍒 정은 🍒

#48 [Feat] #47 - 홈뷰 리뷰 키워드 컬렉션뷰 구현
  GEON-PPANG-iOS/Presentation/Common/StackView/RegionStackView.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeBakeryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/Home/Views/HomeHeaderView.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#50 [Feat] #39 - 필터 선택 플로우 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Application/SceneDelegate.swift
  GEON-PPANG-iOS/Global/Enum/FilterEnum.swift
  GEON-PPANG-iOS/Global/Extensions/UI/CGFloat+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/String+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UIScreen+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UIViewController+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Utils/Utils.swift
  GEON-PPANG-iOS/Presentation/Common/CustomNavigationBar.swift
  GEON-PPANG-iOS/Presentation/Filter/Model/FilterDTO.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterBreadTypeViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterIngredientViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterPurposeViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/Views/FilterCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/Home/Views/HomeTopView.swift
Labels: 🍞 Feat, 🍏 성민 🍏

#54 [Feat] #51 - MyPageVC 구현 완료
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Application/SceneDelegate.swift
  GEON-PPANG-iOS/Global/Enum/MyPageSectionEnum.swift
  GEON-PPANG-iOS/Global/Extensions/Design/UIImage+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Protocol/BakeryTypeProtocol.swift
  GEON-PPANG-iOS/Global/Utils/Utils.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/Model/BakeryListResponseDTO.swift
  GEON-PPANG-iOS/Presentation/Common/Cell/DescriptionCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/MyPage/Model/MyPageDTO.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/ImageWithSubtitleButton.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPageCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPageCollectionViewFooter.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPageCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPagePurposeChipView.swift
  GEON-PPANG-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  GEON-PPANG-iOS/Presentation/Search/Model/SearchResponseDTO.swift
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_profile.imageset/Contents.json
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_profile.imageset/ic_profile 1.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_profile.imageset/ic_profile 2.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/icons/ic_profile.imageset/ic_profile.png
Labels: 🍞 Feat, 🍏 성민 🍏

#53 [Feat] #43 - 마이페이지 내가 쓴 리뷰 UI 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsViewController.swift
  GEON-PPANG-iOS/Presentation/MyReviews/Views/MyReviewsHeaderView.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#46 [Feat] #44 - 공통 바텀시트 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/Common/BottomSheet/BottomSheetAppearView.swift
  GEON-PPANG-iOS/Presentation/Common/BottomSheet/CommonBottomSheet.swift
  GEON-PPANG-iOS/Presentation/Common/Button/CommonButton.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#59 [Feat] #16 - 리뷰 작성 페이지 플로우 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Application/SceneDelegate.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UILabel+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UIViewController+.swift
  GEON-PPANG-iOS/Presentation/Common/NavigationBar/CustomNavigationBar.swift
  GEON-PPANG-iOS/Presentation/Common/View/BottomView.swift
  GEON-PPANG-iOS/Presentation/Common/View/LineView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/Model/WriteReviewDTO.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/BakeryOverviewView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/OptionsCollection/OptionsCollectionView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/OptionsCollection/OptionsCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/OptionsCollection/OptionsCollectionViewFlowLayout.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/OptionsCollection/OptionsCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/ReviewDetailTextView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/ViewController/WriteReviewViewController.swift
Labels: 🍩 Chore, 🍏 성민 🍏

#64 [Setting] #62 - 네트워크 기본 세팅
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Application/SceneDelegate.swift
  GEON-PPANG-iOS/Global/Network/API/API.swift
  GEON-PPANG-iOS/Global/Network/API/Auth/AuthAPI.swift
  GEON-PPANG-iOS/Global/Network/API/Bakery/BakeryAPI.swift
  GEON-PPANG-iOS/Global/Network/API/Bookmark/BookmarkAPI.swift
  GEON-PPANG-iOS/Global/Network/API/Filter/FilterAPI.swift
  GEON-PPANG-iOS/Global/Network/API/Home/HomeAPI.swift
  GEON-PPANG-iOS/Global/Network/API/MyPage/MyPageAPI.swift
  GEON-PPANG-iOS/Global/Network/API/Search/SearchAPI.swift
  GEON-PPANG-iOS/Global/Network/Base/Config.swift
  GEON-PPANG-iOS/Global/Network/Base/GeneralResponse.swift
  GEON-PPANG-iOS/Global/Network/Base/NetworkBase.swift
  GEON-PPANG-iOS/Global/Network/Base/NetworkConstant.swift
  GEON-PPANG-iOS/Global/Network/Base/NetworkLoggerPlugin.swift
  GEON-PPANG-iOS/Global/Network/Base/NetworkResult.swift
  GEON-PPANG-iOS/Global/Network/Base/URLConstant.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Auth/AuthResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/BakeryResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bookmark/BookmarkResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Filter/FilterResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Home/HomeBestBakeryResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/MyPage/MyPageResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/Auth/AuthService.swift
  GEON-PPANG-iOS/Global/Network/Service/Bakery/BakeryService.swift
  GEON-PPANG-iOS/Global/Network/Service/Bookmark/BookmarkService.swift
  GEON-PPANG-iOS/Global/Network/Service/Filter/FilterService.swift
  GEON-PPANG-iOS/Global/Network/Service/Home/HomeService.swift
  GEON-PPANG-iOS/Global/Network/Service/MyPage/MyPageService.swift
  GEON-PPANG-iOS/Global/Network/Service/Search/SearchService.swift
  GEON-PPANG-iOS/Presentation/Home/Model/HomeBestBakeryResponseDTO.swift
  GEON-PPANG-iOS/Presentation/Home/Model/HomeBestReviewResponseDTO.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeBakeryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Resource/Info.plist
Labels: 🍭 Setting, 🍒 정은 🍒

#57 [Feat] #55 - 정렬 바텀시트 생성
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/Global/Enum/SortEnum.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/Model/BakeryListResponseDTO.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/SortBottomSheetViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryFilterView.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/SortBakeryCollectionViewCell.swift
Labels: 🍞 Feat, 🍏 성민 🍏

#60 [Feat] #58 - 리뷰 작성 bottom sheet 생성 & 리뷰 작성 디테일 및 변경된 레이아웃 적용
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Extensions/UI/UICollectionViewCell+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UIViewController+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Utils/Utils.swift
  GEON-PPANG-iOS/Presentation/Common/BottomSheet/BottomSheetAppearView.swift
  GEON-PPANG-iOS/Presentation/Common/View/BottomView.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPageCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/BakeryOverviewView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/OptionsCollection/OptionsCollectionViewFlowLayout.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/ReviewDetailTextView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/WriteReviewBottomSheetView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/ViewController/WriteReviewViewController.swift
Labels: 🍞 Feat, 🍏 성민 🍏

#70 [Feat] #68 - search뷰 API 연결
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Network/API/Search/SearchAPI.swift
  GEON-PPANG-iOS/Global/Network/Base/URLConstant.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Search/SearchResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/Search/SearchService.swift
  GEON-PPANG-iOS/Global/Protocol/BakeryTypeProtocol.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/Model/BakeryListResponseDTO.swift
  GEON-PPANG-iOS/Presentation/Common/Cell/DescriptionCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/MyPage/Model/MyPageDTO.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsViewController.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/Search/Model/SearchResponseDTO.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  GEON-PPANG-iOS/Presentation/Search/Views/SearchNavigationView.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#63 [Feat] #61 - 필터 선택 완료 뷰 완성
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Application/SceneDelegate.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterCompleteViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterIngredientViewController.swift
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_welcome.imageset/img_welcome 1.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_welcome.imageset/img_welcome 2.png
Labels: 🍞 Feat, 🍏 성민 🍏

#73 [Add] #65 - TODO 없애기 위한 PR
  GEON-PPANG-iOS/Presentation/Common/NavigationBar/CustomNavigationBar.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPageCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPagePurposeChipView.swift
Labels: 🍧 Add, 🍏 성민 🍏

#69 [Feat] #66 - 홈 Best 빵집, 리뷰 API 연결
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Network/API/Home/HomeAPI.swift
  GEON-PPANG-iOS/Global/Network/Base/URLConstant.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Home/HomeBestBakeryResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Home/HomeBestReviewResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/Home/HomeService.swift
  GEON-PPANG-iOS/Presentation/Home/Model/HomeBestReviewResponseDTO.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeBakeryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/Tabbar/TabBarController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#75 [Feat] #71 - 저장목록 API 연결
  GEON-PPANG-iOS/Global/Network/API/MyPage/MyPageAPI.swift
  GEON-PPANG-iOS/Global/Network/Base/URLConstant.swift
  GEON-PPANG-iOS/Global/Network/Service/MyPage/MyPageService.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/Model/BakeryListResponseDTO.swift
  GEON-PPANG-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/EmptyCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  GEON-PPANG-iOS/Presentation/WriteReview/ViewController/WriteReviewViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#77 [Feat] #76 - 빵집 리스트 API 연결
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Network/API/Bakery/BakeryAPI.swift
  GEON-PPANG-iOS/Global/Network/Base/URLConstant.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Home/HomeBestBakeryResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/Bakery/BakeryService.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/Model/BakeryListResponseDTO.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryFilterView.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryListTopView.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#79 [Feat] #78 - 필터 선택 API 연결
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Enum/FilterEnum.swift
  GEON-PPANG-iOS/Global/Network/API/Filter/FilterAPI.swift
  GEON-PPANG-iOS/Global/Network/Base/URLConstant.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/BreadRequestType.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/BreadResponseType.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/NutrientRequestType.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/NutrientResponseType.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Filter/FilterRequestDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Filter/FilterResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/Filter/FilterService.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/Model/BakeryListResponseDTO.swift
  GEON-PPANG-iOS/Presentation/Filter/Model/FilterDTO.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterIngredientViewController.swift
  GEON-PPANG-iOS/Presentation/MyPage/Model/MyPageDTO.swift
Labels: 🍞 Feat, 🍏 성민 🍏

#81 [Feat] #72 - 내가 쓴 리뷰 API 연결
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Enum/SortEnum.swift
  GEON-PPANG-iOS/Global/Network/API/Bakery/BakeryAPI.swift
  GEON-PPANG-iOS/Global/Network/API/Filter/FilterAPI.swift
  GEON-PPANG-iOS/Global/Network/API/Home/HomeAPI.swift
  GEON-PPANG-iOS/Global/Network/API/MyPage/MyPageAPI.swift
  GEON-PPANG-iOS/Global/Network/Base/URLConstant.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/BakeryListResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/BreadResponseType.swift
  GEON-PPANG-iOS/Global/Network/DataModel/MyPage/MyReviewsResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Search/SearchResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/MyPage/MyPageService.swift
  GEON-PPANG-iOS/Global/Protocol/BakeryTypeProtocol.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryCollectionViewListCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/Model/BakeryListResponseDTO.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsViewController.swift
  GEON-PPANG-iOS/Presentation/MyReviews/Views/MyReviewsHeaderView.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/EmptyCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#86 [Fix] #82 - 리스트관련 뷰 레이아웃 수정
  GEON-PPANG-iOS/Global/Extensions/Design/UIImage+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UIViewController+.swift
  GEON-PPANG-iOS/Global/Network/API/Search/SearchAPI.swift
  GEON-PPANG-iOS/Global/Network/Service/Search/SearchService.swift
  GEON-PPANG-iOS/Global/Utils/Utils.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryCollectionViewListCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryFilterCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryFilterView.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Views/BakeryListTopView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/RegionStackView.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeBakeryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeBottomCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/Home/Views/HomeHeaderView.swift
  GEON-PPANG-iOS/Presentation/Home/Views/HomeTopView.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsViewController.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/EmptyCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
Labels: 🧊 Fix, 🍒 정은 🍒

#90 [Feat] #56 - 이메일, 비밀번호, 닉네임 UI 구현
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Application/AppDelegate.swift
  GEON-PPANG-iOS/Application/SceneDelegate.swift
  GEON-PPANG-iOS/Global/Extensions/UI/String+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UITextField+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/Common/Button/CommonButton.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/CommonTextView.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/SearchTextField.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/SignInTextField.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/Onboarding/OnboardingViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/Email/EmailViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/NickName/NickNameViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/Password/PasswordViewController.swift
  GEON-PPANG-iOS/Presentation/Tabbar/TabBarController.swift
Labels: 🍞 Feat, 🍒 정은 🍒

#93 [Feat] #45 - 상세 페이지 뷰 구현 및 API 연결
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Extensions/UI/Int+.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UIButton+.swift
  GEON-PPANG-iOS/Global/Network/API/Bakery/BakeryAPI.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/BakeryDetailResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/WrittenReviewsResponseDTO.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/InfoCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/MenuCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/ReviewCategoryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/TitleCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/WrittenReviewsCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/BakeryDetailCollectionViewFooter.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/BakeryDetailCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/ReviewProgressView.swift
  GEON-PPANG-iOS/Presentation/Common/Button/BookmarkButton.swift
  GEON-PPANG-iOS/Presentation/Common/Button/ReviewSortButton.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/BookmarkReviewNumberStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/BreadTypeStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/IconLabelStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/MarkStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/ReviewCategoryStackView.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/ReviewProgressBarStackView.swift
  GEON-PPANG-iOS/Presentation/Common/View/DrawDashLineView.swift
  GEON-PPANG-iOS/Presentation/Common/View/LineView.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Onboarding/ViewControllers/OnboardingViewController.swift
  GEON-PPANG-iOS/Presentation/WriteReview/ViewController/WriteReviewViewController.swift
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_welcome.imageset/img_welcome 1.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/images/img_welcome.imageset/img_welcome 2.png
Labels: 🍞 Feat, 🍎 창균 🍎

#98 [Feat] #85 - 상세페이지의 BottomView 구현 및 리뷰 작성 연결
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Network/API/Bakery/BakeryAPI.swift
  GEON-PPANG-iOS/Global/Network/Base/URLConstant.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/BookmarkRequestDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/BookmarkResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/WriteReviewRequestDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bookmark/BookmarkResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/Bakery/BakeryService.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/Common/View/DetailBottomView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/Model/LikeModel.swift
  GEON-PPANG-iOS/Presentation/WriteReview/Model/RecommendationModel.swift
  GEON-PPANG-iOS/Presentation/WriteReview/Model/SimpleBakeryModel.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/BakeryOverviewView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/ViewController/WriteReviewViewController.swift
Labels: 🍞 Feat, 🍏 성민 🍏

#94 [Feat] #92 - 디테일뷰로 화면 전환 연결
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Cell/BakeryCollectionViewListCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Cell/BakeryFilterCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Cell/SortBakeryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/CommonTextView.swift
  GEON-PPANG-iOS/Presentation/Common/TextField/SignInTextField.swift
  GEON-PPANG-iOS/Presentation/Home/HomeBakeryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/HomeBottomCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/HomeReviewCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/MyReviews/Cell/MyReviewsCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/MyReviews/ViewControllers/MyReviewsViewController.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/Search/Cell/EmptyCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  GEON-PPANG-iOS/Presentation/Search/Views/SearchResultView.swift
  GEON-PPANG-iOS/Presentation/SignIn/Email/EmailViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/NickName/NickNameViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/Password/PasswordViewController.swift
Labels: 🍞 Feat, 🧊 Fix, 🍒 정은 🍒

#91 [Feat] #80 - 마이페이지 API 연결 완료
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Application/SceneDelegate.swift
  GEON-PPANG-iOS/Global/Enum/FilterEnum.swift
  GEON-PPANG-iOS/Global/Network/API/MyPage/MyPageAPI.swift
  GEON-PPANG-iOS/Global/Network/Base/URLConstant.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/BreadRequestType.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/BreadResponseType.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Common/NutrientRequestType.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Filter/FilterRequestDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/MyPage/MyPageResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/MyPage/MyPageService.swift
  GEON-PPANG-iOS/Presentation/Common/Button/CommonButton.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterCompleteViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterIngredientViewController.swift
  GEON-PPANG-iOS/Presentation/Filter/ViewControllers/FilterPurposeViewController.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/MyPage/Model/MyPageDTO.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPageCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/NickName/NickNameViewController.swift
Labels: 🍞 Feat, 🍏 성민 🍏

#83 [Feat] #74 - 리뷰 작성 API 연결
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Extensions/UI/UIViewController+.swift
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Global/Network/API/Bakery/BakeryAPI.swift
  GEON-PPANG-iOS/Global/Network/Base/URLConstant.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/BookmarkRequestDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/BookmarkResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/WriteReviewDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bakery/WriteReviewRequestDTO.swift
  GEON-PPANG-iOS/Global/Network/DataModel/Bookmark/BookmarkResponseDTO.swift
  GEON-PPANG-iOS/Global/Network/Service/Bakery/BakeryService.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/Common/BottomSheet/BottomSheetAppearView.swift
  GEON-PPANG-iOS/Presentation/Common/View/DetailBottomView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/Model/LikeModel.swift
  GEON-PPANG-iOS/Presentation/WriteReview/Model/RecommendationModel.swift
  GEON-PPANG-iOS/Presentation/WriteReview/Model/SimpleBakeryModel.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/BakeryOverviewView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/ReviewDetailTextView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/ViewController/WriteReviewViewController.swift
Labels: 🍞 Feat, 🍏 성민 🍏

#103 [Feat] #99 - 온보딩 뷰 레이아웃 기기 별 대응 추가
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/Application/AppDelegate.swift
  GEON-PPANG-iOS/Application/SceneDelegate.swift
  GEON-PPANG-iOS/Global/Extensions/UI/UILabel+.swift
  GEON-PPANG-iOS/Presentation/Onboarding/ViewControllers/OnboardingViewController.swift
Labels: 🍞 Feat, 🍎 창균 🍎

#97 [Feat] #96 - App Icon 및 display 이름 설정
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/100.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/1024.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/114.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/120.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/144.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/152.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/167.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/180.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/20.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/29.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/40.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/50.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/57.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/58.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/60.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/72.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/76.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/80.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/87.png
  GEON-PPANG-iOS/Resource/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 🍞 Feat, 🍒 정은 🍒

#105 [Feat] #101 - 상세페이지 남은 API 연결
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/InfoCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/BakeryDetailCollectionViewHeader.swift
Labels: 🍞 Feat, 🍎 창균 🍎

#108 [Feat] #102 - 상세페이지 전체적인 레이아웃 수정
  GEON-PPANG-iOS/Global/Extensions/UI/UICollectionViewCell+.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/MenuCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/ReviewCategoryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/WrittenReviewsCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Views/BakeryDetailCollectionViewFooter.swift
Labels: 🍞 Feat, 🍎 창균 🍎

#106 [Feat] #104 - 자체 QA 진행 후 수정
  GEON-PPANG-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  GEON-PPANG-iOS/Application/SceneDelegate.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/Cell/TitleCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Common/BottomSheet/CommonBottomSheet.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPageCollectionViewFooter.swift
  GEON-PPANG-iOS/Presentation/MyPage/View/MyPageCollectionViewHeader.swift
  GEON-PPANG-iOS/Presentation/SignIn/Email/EmailViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/Password/PasswordViewController.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/ReviewDetailTextView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/View/WriteReviewBottomSheetView.swift
  GEON-PPANG-iOS/Presentation/WriteReview/ViewController/WriteReviewViewController.swift
Labels: 🍞 Feat, 🍏 성민 🍏

#109 [Feat] #100 - 토스트 메세지 구현
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
Labels: 🍞 Feat, 🍎 창균 🍎

#107 [Fix] #95 - QA반영 디자인 및 로직 수정
  GEON-PPANG-iOS.xcodeproj/project.pbxproj
  GEON-PPANG-iOS/Global/Literals/Strings.swift
  GEON-PPANG-iOS/Presentation/BakeryDetail/ViewControllers/BakeryDetailViewController.swift
  GEON-PPANG-iOS/Presentation/BakeryList/Cell/BakeryCollectionViewListCell.swift
  GEON-PPANG-iOS/Presentation/BakeryList/ViewControllers/BakeryListViewController.swift
  GEON-PPANG-iOS/Presentation/Common/StackView/RegionStackView.swift
  GEON-PPANG-iOS/Presentation/Home/HomeBakeryCollectionViewCell.swift
  GEON-PPANG-iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  GEON-PPANG-iOS/Presentation/MySavedBakery/ViewControllers/MySavedBakeryViewController.swift
  GEON-PPANG-iOS/Presentation/Search/ViewControllers/SearchViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/Email/EmailViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/NickName/NickNameViewController.swift
  GEON-PPANG-iOS/Presentation/SignIn/Password/PasswordViewController.swift
Labels: 🧊 Fix, 🍒 정은 🍒
